version: '3.7'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis:/data
