version: '3.7'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
      target: prod
    env_file:
      - ./docker/env/backend.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      target: prod
    volumes:
      - './docker/frontend/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend

  ws:
    build:
      context: .
      dockerfile: packages/ws/Dockerfile
      target: prod
    env_file:
      - ./docker/env/ws.env
    depends_on:
      - redis

  haproxy:
    image: haproxy:alpine
    ports:
      - 8080:8080
    volumes:
      - ./docker/haproxy/haproxy.prod.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - frontend
      - backend
      - ws

volumes:
  postgres:
  redis:
