#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn workspace @chat-app/backend lint && yarn workspace @chat-app/backend format
yarn workspace @chat-app/frontend lint && yarn workspace @chat-app/frontend format
yarn workspace @chat-app/ws lint && yarn workspace @chat-app/ws format
